### ISSUE TITLE
Filters Spring Cloud Gateway MVC 

### ISSUE THREAD

**Issue by bharatnpti** [spencergibb/spring-cloud-gateway-mvc-sample#3]
Question

How to write filter in Spring cloud gateway mvc.

In Zuul we have @ZuulFilter and in Spring Cloud Gateway we have @GatewayFilter

What is the replacement for above in Spring Cloud Gateway MVC

**Comment by spencergibb** [comment]
Closing in favor of https://github.com/spring-cloud/spring-cloud-gateway/issues/3143
